### ISSUE TITLE
ISO端 自动首次刷新的时候下拉会同时执行

### ISSUE THREAD

**Issue by jijkbird** [xuelongqy/flutter_easyrefresh#359]
════════ Exception caught by animation library ═════════════════════════════════════════════════════
The following assertion was thrown while notifying listeners for AnimationController:
EasyRefreshPhysics.applyBoundaryConditions returned invalid overscroll value.

The method was called to consider a change from 46599.01388888882 to 46571.18515503443, which is a delta of -27.8 units. However, it returned an overscroll of 32.2 units, which has a greater magnitude than the delta. The applyBoundaryConditions method is only supposed to reduce the possible range of movement, not increase it.
The scroll extents are 0.0 .. 46539.01388888882, and the viewport dimension is 545.0.
When the exception was thrown, this was the stack: 
#0      ScrollPosition.applyBoundaryConditions.<anonymous closure> (package:flutter/src/widgets/scroll_position.dart:405:9)
#1      ScrollPosition.applyBoundaryConditions (package:flutter/src/widgets/scroll_position.dart:417:6)
#2      ScrollPosition.setPixels (package:flutter/src/widgets/scroll_position.dart:230:33)
#3      ScrollPositionWithSingleContext.setPixels (package:flutter/src/widgets/scroll_position_with_single_context.dart:85:18)
#4      BallisticScrollActivity.applyMoveTo (package:flutter/src/widgets/scroll_activity.dart:558:21)
...
The AnimationController notifying listeners was: AnimationController#dc518(▶ 46571.185; for BallisticScrollActivity)
════════════════════════════════════════════════════════════════════════════════════════════════════
flutter: 320

**Comment by xuelongqy** [comment]
请尝试2.1.6版本

**Comment by woxihejinghao** [comment]
嵌套在NestedScrollView下面，还是有点问题，会下拉

**Comment by woxihejinghao** [comment]
已经是2.1.6版本

**Comment by dmskys** [comment]
同样的问题 而且还遇到这个
════════ Exception caught by foundation library ════════════════════════════════════════════════════
The following assertion was thrown while dispatching notifications for ValueNotifier<TaskState>:
setState() or markNeedsBuild() called during build.

This EasyRefresh widget cannot be marked as needing to build because the framework is already in the process of building widgets.  A widget can be marked as needing to be built during the build phase only if one of its ancestors is currently building. This exception is allowed because the framework builds parent widgets before children, which means a dirty descendant will always be built. Otherwise, the framework might not visit this widget during this build phase.
The widget on which setState() or markNeedsBuild() was called was: EasyRefresh
  state: _EasyRefreshState#4f7ca
The widget which was currently being built when the offending call was made was: LayoutBuilder
  renderObject: _RenderLayoutBuilder#e4279 relayoutBoundary=up2 NEEDS-PAINT
When the exception was thrown, this was the stack: 
#0      Element.markNeedsBuild.<anonymous closure> (package:flutter/src/widgets/framework.dart:4292:11)
#1      Element.markNeedsBuild (package:flutter/src/widgets/framework.dart:4307:6)
#2      State.setState (package:flutter/src/widgets/framework.dart:1264:14)
#3      _EasyRefreshState.initState.<anonymous closure> (package:flutter_easyrefresh/src/refresher.dart:286:9)
#4      ChangeNotifier.notifyListeners (package:flutter/src/foundation/change_notifier.dart:226:25)
...
The ValueNotifier<TaskState> sending notification was: ValueNotifier<TaskState>#cd8f4(Instance of 'TaskState')
════════════════════════════════════════════════════════════════════════════════════════════════════

════════ Exception caught by foundation library ════════════════════════════════════════════════════
setState() or markNeedsBuild() called during build.
════════════════════════════════════════════════════════════════════════════════════════════════════

**Comment by SmileJason** [comment]
同问，怎样解决？

**Comment by xuelongqy** [comment]
v2.1.7已修复
